### PR TITLE
chore: cleanup in prep for uds-core baseline changes

### PR DESCRIPTION
**Pull request by MxNxPx**

### CODE REVIEW

**Review by mikevanhemert — APPROVED** [review]
Marie Kondo approved decluttering

**Review by mjnagel — APPROVED** [review]
Seems legit! 💣

**Comment by anthonywendt** [comment]
I'm confused about what took place here. Inside joke? I want to be a part of one some day.

**Comment by mjnagel** [comment]
@anthonywendt this was meant to be a cleanup of the fresh start repo for sonarqube, following the unbrella/UDS Core patterns. It was not meant to be in this repo I don't think though, instead meant for a fork of the repo, which I believe was here - https://github.com/defenseunicorns/uds-package-sonarqube

**Comment by anthonywendt** [comment]
> @anthonywendt this was meant to be a cleanup of the fresh start repo for sonarqube, following the unbrella/UDS Core patterns. It was not meant to be in this repo I don't think though, instead meant for a fork of the repo, which I believe was here - https://github.com/defenseunicorns/uds-package-sonarqube

Haha makes sense. I figured as much. I just actually looked at my sea of github emails and saw this.

**Comment by anthonywendt** [comment]
> insidejoke [ insidejoke ](https://private-user-images.githubusercontent.com/40472433/295973656-8585e091-ec12-4886-ad3d-8c4105396868.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAyODgsIm5iZiI6MTcwNDk4OTk4OCwicGF0aCI6Ii80MDQ3MjQzMy8yOTU5NzM2NTYtODU4NWUwOTEtZWMxMi00ODg2LWFkM2QtOGM0MTA1Mzk2ODY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNmNmYzVlZTNmMjUwODkyMGRhNThmMDBjZWE1OGI4MjVkNjU1NzNjYmM1Nzg1ZTEwZjRhODQ0MDcxZTMxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TOU04jKccDkFehY3xROpk8jJ3I_1x-2lcu18RIRJvU) [ ](https://private-user-images.githubusercontent.com/40472433/295973656-8585e091-ec12-4886-ad3d-8c4105396868.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5OTAyODgsIm5iZiI6MTcwNDk4OTk4OCwicGF0aCI6Ii80MDQ3MjQzMy8yOTU5NzM2NTYtODU4NWUwOTEtZWMxMi00ODg2LWFkM2QtOGM0MTA1Mzk2ODY4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNmNmYzVlZTNmMjUwODkyMGRhNThmMDBjZWE1OGI4MjVkNjU1NzNjYmM1Nzg1ZTEwZjRhODQ0MDcxZTMxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TOU04jKccDkFehY3xROpk8jJ3I_1x-2lcu18RIRJvU)
> 
> @mjnagel said it kindly, i mucked up a PR and opened against the forked upstream (this repo) instead of origin. please forgive me!

Don't apologize! I just wanted to lure you all back in so I could feel like I was part of your friend group. My wife saw me chuckle while reading your reply. She asked whats so funny and I said, "Oh just some silly inside jokes with my friends". She muddled under her breath, "wow, he's not a loser". Although maybe she said "wow, what a loser". Either way, thank you!

**Comment by MxNxPx** [comment]
> 
> Don't apologize! I just wanted to lure you all back in so I could feel like I was part of your friend group. My wife saw me chuckle while reading your reply. She asked whats so funny and I said, "Oh just some silly inside jokes with my friends". She muddled under her breath, "wow, he's not a loser". Although maybe she said "wow, what a loser". Either way, thank you!

@anthonywendt hahaha!!!  next time someone opens a bogus PR (probably will be from me again), i'm hoping someone closes it with a single `i love inside jokes` comment.

**Pull request closed without merging**
